on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Evaluator:
    runs-on: self-hosted
    name: Evaluator Job
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Fetch C# evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/csharp-evaluator-action
          ref: v1
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/csharp-evaluator

      - name: Fetch Store evaluation
        uses: actions/checkout@v2
        with:
          repository: betrybe/store-evaluation-action
          ref: v4.2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/store-evaluation

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: 'main'

      - name: Run C# evaluator
        id: evaluator
        uses: ./.github/actions/csharp-evaluator
        with:
          pr_author_username: ${{ github.event.pull_request.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}

      - name: Run Store evaluation
        uses: ./.github/actions/store-evaluation
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: staging
          pr-number: ${{ github.event.pull_request.number }}
